spring.application.name=eurekaserver
server.port=8761

eureka.client.register-with-eureka=false 
 #pour n'est pas enrigister sur lui meme

#pour n'est pas chercher l'infroamtion sur les autres  microservices enrigistrer
eureka.client.fetch-registry=false

spring.cloud.config.enabled=false
eureka.server.enable-self-preservation=true